title: OCI TAO
email: info@objectcomputing.com
description: >
  OCI TAO is OCI's supported release of the ACE ORB. OCI TAO is freely available, both in terms
  of spirit and cost. OCI provides fee based, commercial support for TAO including older versions
  thereby facilitating support for the duration of long-lifespan product. For more information
  about OCI's support offering contact mailto:info@objectcomputing.com
baseurl: "https://objectcomputing.github.io/OCITAO"
twitter_username: ObjectComputing
github_username:  objectcomputing

# Build settings
markdown: kramdown

# github-metadata
repository: objectcomputing/OCITAO
gems: ['jekyll-github-metadata', 'octopress-debugger' ]

#OCI web metadata
product_logo_url: ../images/TAO-logo-1.png
objectcomputing_product_page: https://www.objectcomputing.com/products/tao/
